## ============================================================
## 05_List_of_candidates.R
##
## Purpose
##   Export 4 per-photoperiod CSV files listing PPR-only oscillators and
##   whether each call is "robust" or "candidate".
##
##   Definitions (from final_consensus_table.csv generated by Script 04):
##     - robust    := consensus_rhythmic == TRUE
##     - candidate := consensus_candidate == TRUE AND NOT robust
##
## Inputs
##   - tables/final_consensus_table.csv   (from Script 04 rhythmicity analysis)
##   - data_clean/PPR_only_genelist.txt   (from Script 02 gene list split)
##
## Outputs (CSV; written to tables/)
##   - tables/PPR_oscillators_12L12D.csv
##   - tables/PPR_oscillators_12L12D_LL.csv
##   - tables/PPR_oscillators_16L8D.csv
##   - tables/PPR_oscillators_8L16D.csv
##
## Output columns
##   - AGI
##   - status   ("robust" or "candidate")
##
## Notes
##   - Parses logicals robustly in case they are stored as TRUE/FALSE,
##     "TRUE"/"FALSE", or 1/0 in the CSV.
## ============================================================

suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
})

## ----------------------------
## Config
## ----------------------------
final_file <- "tables/final_consensus_table.csv"
ppr_file   <- "data_clean/PPR_only_genelist.txt"

conditions <- c("12L12D", "12L12D_LL", "16L8D", "8L16D")

dir.create("tables", showWarnings = FALSE, recursive = TRUE)
stopifnot(file.exists(final_file), file.exists(ppr_file))

## ----------------------------
## Helpers
## ----------------------------
as_logical_robust <- function(x) {
  if (is.logical(x)) return(ifelse(is.na(x), FALSE, x))
  x2 <- tolower(trimws(as.character(x)))
  x2 %in% c("true", "t", "1", "yes", "y")
}

## ----------------------------
## Load PPR-only gene list
## ----------------------------
ppr_only <- readLines(ppr_file, warn = FALSE) |>
  trimws() |>
  toupper()
ppr_only <- ppr_only[nzchar(ppr_only)]

## ----------------------------
## Load final consensus table
## ----------------------------
final_cons <- fread(final_file, data.table = FALSE) %>%
  mutate(
    AGI = toupper(trimws(sub("\\..*$", "", AGI))),
    condition = as.character(condition),
    
    consensus_rhythmic  = as_logical_robust(consensus_rhythmic),
    consensus_candidate = as_logical_robust(consensus_candidate)
  )

## ----------------------------
## Export per-condition CSVs
## ----------------------------
for (cond in conditions) {
  
  df_cond <- final_cons %>%
    filter(condition == cond, AGI %in% ppr_only) %>%
    mutate(
      status = case_when(
        consensus_rhythmic == TRUE ~ "robust",
        consensus_candidate == TRUE ~ "candidate",
        TRUE ~ NA_character_
      )
    ) %>%
    filter(!is.na(status)) %>%
    distinct(AGI, status) %>%
    arrange(factor(status, levels = c("robust", "candidate")), AGI)
  
  out_csv <- file.path("tables", paste0("PPR_oscillators_", cond, ".csv"))
  write.csv(df_cond, out_csv, row.names = FALSE, quote = TRUE)
  
  cat(sprintf("[%-9s] wrote %4d genes -> %s\n", cond, nrow(df_cond), out_csv))
}

cat("\nDone. Wrote per-condition CSV files to tables/.\n")
