## ============================================================
## 09_Top10_robust_PPR_priority.R
##
## Goal:
##   Rank PPR genes by a composite priority score emphasizing:
##     1) rhythmicity strength (padj across supporting gears; per method)
##     2) robustness across photoperiods
##     3) phase consistency across photoperiods (circular SD)
##     4) promoter motif evidence (total hits + motif-type diversity)
##
## Inputs (expected):
##   - tables/final_consensus_table.csv
##   - data_clean/PPR_only_genelist.txt
##   - tables/motif_scan_per_photoperiod/motif_counts_<condition>.csv  (Script 06)
## Optional (for strength score; generated by Script 04):
##   - tables/support_by_gene_condition_gear.csv
##   - tables/method_results_long.csv
##
## Outputs:
##   - tables/PPR_priority_ranking.csv
##   - tables/Top10_robust_PPRs.csv
## ============================================================

suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
})

dir.create("tables", showWarnings = FALSE, recursive = TRUE)

## ----------------------------
## 0) Paths + settings
## ----------------------------

final_consensus_path <- "tables/final_consensus_table.csv"
ppr_list_path        <- "data_clean/PPR_only_genelist.txt"
motif_dir            <- "tables/motif_scan_per_photoperiod"

support_by_gear_path <- "tables/support_by_gene_condition_gear.csv"
method_results_path  <- "tables/method_results_long.csv"

stopifnot(file.exists(final_consensus_path), file.exists(ppr_list_path))

conditions <- c("12L12D","12L12D_LL","16L8D","8L16D")
vote_methods <- c("RAIN","JTK","COSINOR")

## Weights (sum to 1.0)
w_strength    <- 0.55
w_photoperiod <- 0.20
w_phase       <- 0.15
w_motif       <- 0.10

## Caps for normalization (keeps scores stable + interpretable)
cap_strength_sum <- 24   # 4 photoperiods * (cap 6 per condition)
cap_motif_hits   <- 12   # cap total motif hits used for scoring

## ----------------------------
## 1) Helpers
## ----------------------------

.clean_agi <- function(x) toupper(trimws(sub("\\..*$", "", x)))

.safe_fread <- function(path) {
  if (!file.exists(path)) return(NULL)
  data.table::fread(path, data.table = FALSE)
}

circ_sd_hours <- function(h, period = 24) {
  h <- h[is.finite(h)]
  if (length(h) < 2) return(Inf)
  ang <- 2*pi*h/period
  C <- mean(cos(ang)); S <- mean(sin(ang))
  R <- sqrt(C^2 + S^2)
  if (!is.finite(R) || R <= 0) return(Inf)
  sd_rad <- sqrt(-2 * log(R))
  sd_rad * (period/(2*pi))
}

## Score phase consistency: 0..30 (best = low circSD)
phase_score_raw <- function(circ_sd_h) {
  if (!is.finite(circ_sd_h) || is.infinite(circ_sd_h)) return(0)
  # full points if <=1h; linearly decay to 0 at 4h
  if (circ_sd_h <= 1) return(30)
  if (circ_sd_h >= 4) return(0)
  30 * (1 - (circ_sd_h - 1)/(4 - 1))
}

## Motif score: 0..30 (simple + transparent)
motif_score_raw <- function(total_hits_all, n_types_present) {
  th <- ifelse(is.finite(total_hits_all), total_hits_all, 0)
  nt <- ifelse(is.finite(n_types_present), n_types_present, 0)
  th_cap <- pmin(th, cap_motif_hits)
  # primary = hit burden, small bonus for diversity
  pmin(30, 2.5 * th_cap + 0.5 * pmin(nt, 6))
}

## Convert raw sub-scores to 0..100
norm_0_100 <- function(x, max_x) {
  ifelse(!is.finite(x), 0, 100 * pmin(pmax(x, 0), max_x) / max_x)
}

## ----------------------------
## 2) Load PPR list + consensus table
## ----------------------------

ppr_only <- readLines(ppr_list_path, warn = FALSE) |>
  trimws() |>
  toupper()
ppr_only <- ppr_only[nzchar(ppr_only)]

final_cons <- data.table::fread(final_consensus_path, data.table = FALSE) %>%
  mutate(
    AGI = .clean_agi(AGI),
    condition = as.character(condition),
    phase_est = suppressWarnings(as.numeric(phase_est)),
    consensus_rhythmic       = as.logical(consensus_rhythmic),
    consensus_rhythmic_phase = as.logical(consensus_rhythmic_phase),
    consensus_candidate      = as.logical(consensus_candidate)
  ) %>%
  filter(AGI %in% ppr_only, condition %in% conditions)

## ROBUST definition per condition:
## Prefer phase-consistent robust; otherwise accept robust
final_cons <- final_cons %>%
  mutate(is_robust = (consensus_rhythmic_phase %in% TRUE) | (consensus_rhythmic %in% TRUE))

robust_by_gene <- final_cons %>%
  filter(is_robust, is.finite(phase_est)) %>%
  group_by(AGI) %>%
  summarise(
    n_photoperiods_robust = n_distinct(condition),
    conditions_robust = paste(sort(unique(condition)), collapse = ";"),
    phase_circSD_h = circ_sd_hours(phase_est, period = 24),
    .groups = "drop"
  ) %>%
  # keep only genes robust in >=1 photoperiod
  filter(n_photoperiods_robust >= 1)

## ----------------------------
## 3) Load motif tables (promoters)
## ----------------------------

motif_files <- file.path(motif_dir, paste0("motif_counts_", conditions, ".csv"))
motif_tabs <- lapply(seq_along(conditions), function(i) {
  ff <- motif_files[i]
  if (!file.exists(ff)) return(NULL)
  x <- .safe_fread(ff)
  if (is.null(x)) return(NULL)
  x$AGI <- .clean_agi(x$AGI)
  x$condition <- conditions[i]
  x
})
motif_tabs <- Filter(Negate(is.null), motif_tabs)

motif_cols <- c("AAATATCT","AATATCT","AAAAATCT","AACCAC","CCACAC","CACGTG")

motif_by_gene <- NULL
if (length(motif_tabs) > 0) {
  motif_all <- bind_rows(motif_tabs)
  
  # Promoter sequence for a gene is the same across conditions; take max across files defensively.
  motif_by_gene <- motif_all %>%
    group_by(AGI) %>%
    summarise(
      n_entries = max(n_entries, na.rm = TRUE),
      across(all_of(motif_cols), ~ max(.x, na.rm = TRUE)),
      total_hits_all = max(total_hits_all, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(
      total_hits_all = ifelse(is.finite(total_hits_all), total_hits_all, 0),
      n_motif_types_present = rowSums(across(all_of(motif_cols), ~ (.x > 0)))
    )
} else {
  warning("No motif tables found in ", motif_dir, ". Motif score will be 0.")
  motif_by_gene <- data.frame(
    AGI = robust_by_gene$AGI,
    n_entries = NA_integer_,
    AAATATCT = 0L, AATATCT = 0L, AAAAATCT = 0L, AACCAC = 0L, CCACAC = 0L, CACGTG = 0L,
    total_hits_all = 0,
    n_motif_types_present = 0L,
    stringsAsFactors = FALSE
  )
}

## ----------------------------
## 4) Rhythmicity strength (padj across SUPPORTING gears)
## ----------------------------

has_strength_inputs <- file.exists(support_by_gear_path) && file.exists(method_results_path)

if (!has_strength_inputs) {
  warning(
    "Strength tables not found. To enable rhythmicity strength scoring, generate:\n",
    "  - ", support_by_gear_path, "\n",
    "  - ", method_results_path, "\n",
    "by running Script 04. Strength score will be 0."
  )
}

strength_by_gene <- robust_by_gene %>%
  mutate(strength_sum = 0, strength_score = 0)

if (has_strength_inputs) {
  
  sup <- .safe_fread(support_by_gear_path)
  meth <- .safe_fread(method_results_path)
  
  stopifnot(
    all(c("AGI","condition","gear_id","support_votes_strict") %in% colnames(sup)),
    all(c("AGI","condition","gear_id","method","padj") %in% colnames(meth))
  )
  
  sup$AGI <- .clean_agi(sup$AGI)
  sup$condition <- as.character(sup$condition)
  
  meth$AGI <- .clean_agi(meth$AGI)
  meth$condition <- as.character(meth$condition)
  meth$method <- toupper(as.character(meth$method))
  meth$padj <- suppressWarnings(as.numeric(meth$padj))
  
  # Build condition-level strength for each (AGI, condition) that is ROBUST
  robust_pairs <- final_cons %>%
    filter(is_robust) %>%
    distinct(AGI, condition)
  
  cond_strength <- lapply(seq_len(nrow(robust_pairs)), function(i) {
    g <- robust_pairs$AGI[i]
    cnd <- robust_pairs$condition[i]
    
    sup_g <- sup[sup$AGI == g & sup$condition == cnd, , drop = FALSE]
    gears_keep <- unique(sup_g$gear_id[sup_g$support_votes_strict %in% TRUE])
    
    if (length(gears_keep) == 0) {
      return(data.frame(AGI = g, condition = cnd, condition_strength = NA_real_, stringsAsFactors = FALSE))
    }
    
    meth_g <- meth[
      meth$AGI == g &
        meth$condition == cnd &
        meth$gear_id %in% gears_keep &
        meth$method %in% vote_methods &
        is.finite(meth$padj),
      ,
      drop = FALSE
    ]
    
    if (nrow(meth_g) == 0) {
      return(data.frame(AGI = g, condition = cnd, condition_strength = NA_real_, stringsAsFactors = FALSE))
    }
    
    # median padj per method across supporting gears
    per_method <- meth_g %>%
      group_by(method) %>%
      summarise(median_padj = median(padj, na.rm = TRUE), .groups = "drop") %>%
      mutate(neglog10_median = pmax(0, -log10(median_padj)))
    
    # condition strength = mean across methods present (transparent, not inferential)
    data.frame(
      AGI = g,
      condition = cnd,
      condition_strength = mean(per_method$neglog10_median, na.rm = TRUE),
      stringsAsFactors = FALSE
    )
  })
  
  cond_strength <- bind_rows(cond_strength)
  
  strength_by_gene <- cond_strength %>%
    group_by(AGI) %>%
    summarise(
      strength_sum = sum(condition_strength, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(
      strength_sum = ifelse(is.finite(strength_sum), strength_sum, 0),
      strength_score = norm_0_100(strength_sum, cap_strength_sum)
    )
}

## ----------------------------
## 5) Combine features + compute priority score
## ----------------------------

score_table <- robust_by_gene %>%
  left_join(motif_by_gene, by = "AGI") %>%
  left_join(strength_by_gene, by = "AGI") %>%
  mutate(
    # raw sub-scores
    photoperiod_score = 15 * n_photoperiods_robust,         # 0..60
    phase_score       = vapply(phase_circSD_h, phase_score_raw, numeric(1)),  # 0..30
    motif_score       = motif_score_raw(total_hits_all, n_motif_types_present), # 0..30
    
    # normalized 0..100 components
    photoperiod_score_100 = norm_0_100(photoperiod_score, 60),
    phase_score_100       = norm_0_100(phase_score, 30),
    motif_score_100       = norm_0_100(motif_score, 30),
    
    # final weighted priority
    priority_score =
      w_strength    * strength_score +
      w_photoperiod * photoperiod_score_100 +
      w_phase       * phase_score_100 +
      w_motif       * motif_score_100
  ) %>%
  arrange(desc(priority_score),
          desc(strength_score),
          desc(n_photoperiods_robust),
          desc(total_hits_all),
          AGI) %>%
  select(
    AGI,
    n_photoperiods_robust,
    conditions_robust,
    phase_circSD_h,
    strength_sum,
    strength_score,
    n_entries,
    all_of(motif_cols),
    total_hits_all,
    n_motif_types_present,
    photoperiod_score,
    phase_score,
    motif_score,
    priority_score
  )

## ----------------------------
## 6) Write outputs
## ----------------------------

out_all  <- "tables/PPR_priority_ranking.csv"
out_top10 <- "tables/Top10_robust_PPRs.csv"

write.csv(score_table, out_all, row.names = FALSE)

top10 <- head(score_table, 10)
write.csv(top10, out_top10, row.names = FALSE)

cat("\nWrote full ranking:\n  ", out_all, "\n", sep = "")
cat("Wrote top10:\n  ", out_top10, "\n\n", sep = "")

cat("Top 10 candidates:\n")
print(top10, row.names = FALSE)
